<?php
$relational = Array(
	"approx.gif" => array("\\approx "),
	"asymp.gif" => array("\\asymp "),
	"cong.gif" => array("\\cong "),
	"dashv.gif" => array("\\dashv "),
	"doteq.gif" => array("\\doteq "),
	"eq.gif" => array("= "),
	"equiv.gif" => array("\\equiv "),
	"frown.gif" => array("\\frown "),
	"geq.gif" => array("\\geq "),
	"geqslant.gif" => array("\\geqslant "),
	"gg.gif" => array("\\gg "),
	"gt.gif" => array("\\gt "),
	"hline.gif" => array("| "),
	"leq.gif" => array("\\leq "),
	"leqslant .gif" => array("\\leqslant "),
	"ll.gif" => array("\\ll "),
	"lt.gif" => array("\\lt "),
	"models.gif" => array("\\models "),
	"neq.gif" => array("\\neq "),
	"ngeqslant .gif" => array("\\ngeqslant "),
	"ngtr.gif" => array("\\ngtr "),
	"nleqslant .gif" => array("\\nleqslant "),
	"nless.gif" => array("\\nless "),
	"notequiv.gif" => array("\\not\\equiv "),
	"oversetdiff.png" => array("\overset{\underset{\mathrm{def}}{}}{=} "),
	"parallel.gif" => array("\\parallel "),
	"perp.gif" => array("\\perp "),
	"prec.gif" => array("\\prec "),
	"preceq.gif" => array("\\preceq "),
	"sim.gif" => array("\\sim "),
	"simeq.gif" => array("\\simeq "),
	"smile.gif" => array("\\smile "),
	"succ.gif" => array("\\succ "),
	"succeq.gif" => array("\\succeq "),
	"vdash.gif" => array("\\vdash")
);
?>