<?php
$lowercase_greek = Array(
				"alpha.gif" => array("\\alpha"),
				"beta.gif" => array("\\beta"),
				"chi.gif" => array("\\chi"),
				"delta.gif" => array("\\delta"),
				"epsilon.gif" => array("\\epsilon"),
				"eta.gif" => array("\\eta"),
				"gamma.gif" => array("\\gamma"),
				"iota.gif" => array("\\iota"),
				"kappa.gif" => array("\\kappa"),
				"lambda.gif" => array("\\lambda"),
				"mu.gif" => array("\\mu"),
				"nu.gif" => array("\\nu"),
				"omega.gif" => array("\\omega"),
				"phi.gif" => array("\\phi"),
				"pi.gif" => array("\\pi"),
				"psi.gif" => array("\\psi"),
				"rho.gif" => array("\\rho"),
				"sigma.gif" => array("\\sigma"),
				"tau.gif" => array("\\tau"),
				"theta.gif" => array("\\theta"),
				"upsilon.gif" => array("\\upsilon"),
				"varepsilon.gif" => array("\\varepsilon"),
				"varphi.gif" => array("\\varphi"),
				"varpi.gif" => array("\\varpi"),
				"varrho.gif" => array("\\varrho"),
				"varsigma .gif" => array("\\varsigma"),
				"vartheta.gif" => array("\\vartheta"),
				"xi.gif" => array("\\xi"),
				"zeta.gif" => array("\\zeta")
		);
?>